### ISSUE TITLE
Implement Paketo Stacks RFC 0004: Jammy Jellyfish

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/jammy-full-stack#1]
[Paketo Stacks RFC 0004](https://github.com/paketo-buildpacks/rfcs/blob/ba9273ded6c65274276677b1ad5db5e61029060d/text/stacks/0004-jammy-jellyfish.md) states that Paketo should support a "full" stack on top of Ubuntu Jammy Jellyfish. To implement this RFC:

- [x] Determine which OS packages should be installed on the Full Jammy stack. These may be identical to those installed on the bionic Full stack. (See [the bionic Full repo](https://github.com/paketo-buildpacks/full-stack-release))
- [x] Create a [stack descriptor file](https://github.com/paketo-buildpacks/rfcs/blob/ba9273ded6c65274276677b1ad5db5e61029060d/text/stacks/0003-stack-descriptor.md) for this stack and check it into this repo. The descriptor should have the following attributes:
    - stack id: `io.buildpacks.stacks.jammy`
    - the UID for `build` and `run` phases should differ (but be in the same group)
- [x] Set up automation on this repo that builds the stack using `jam create-stack` and publishes the stack to the appropriate tags:
    - `paketobuildpacks/build-jammy-full:latest`
    - `paketobuildpacks/build-jammy-full:1.2.3`
    - `paketobuildpacks/run-jammy-full:latest`
    - `paketobuildpacks/run-jammy-full:1.2.3`

**Comment by robdimsdale** [comment]
With the [release of `v0.0.3`](https://github.com/paketo-buildpacks/jammy-full-stack/releases/tag/v0.0.3) we can call this initial implementation complete. Closing.
