### ISSUE TITLE
Investigate why Jammy Full stack creation uses so much memory

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/jammy-full-stack#3]
In implementing https://github.com/paketo-buildpacks/jammy-full-stack/pull/2, the acceptance tests were failing due to the stack creation step using more memory than allocated for a GHA run.

As a workaround, @robdimsdale increased swap space memory for the step using a [swap space increase action](https://github.com/paketo-buildpacks/jammy-full-stack/blob/594e2e004b3d76f0ec65094cb67342e3c0a28787/.github/workflows/test-pull-request.yml#L21-L24).

Ideally, we should pinpoint what's going on during the Jammy Full stack creation with `jam create-stack` and modify it to use less memory. This is likely a change in the `jam` code base, and then the use of the `pierotofy/set-swap-space` action in the workflows in this repository can be removed.

More context can be found in [this Slack thread](https://paketobuildpacks.slack.com/archives/C03K61JJ57A/p1658777144258399)

**Comment by sophiewigmore** [comment]
resolved by https://github.com/paketo-buildpacks/jam/pull/94

**Comment by ryanmoran** [comment]
@sophiewigmore I added a flag to `jam` to get this alternative behavior, but the existing behavior is still the default. Do we need to track work to allow workflows to specify this differently for full vs. base or tiny which we'd likely want to keep the default?
